version: '3.7'
services:
  gateway:
    container_name: rd_gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    dns: 8.8.8.8
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    ports:
      - 8000:8000 #can be removed
    networks:
      - vpc

  order:
    container_name: rd_order
    build:
      context: ./order
      dockerfile: Dockerfile
    dns: 8.8.8.8
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    links:
      - order_db
    networks:
      - vpc

  voucher:
    container_name: rd_voucher
    build:
      context: ./voucher
      dockerfile: Dockerfile
    dns: 8.8.8.8
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    links:
      - voucher_db
    networks:
      - vpc

  order_db:
    container_name: rd_order_db
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/data/order_db:/var/lib/mysql
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db
      MYSQL_PASSWORD: db@123
      TZ: UTC
    networks:
      - vpc

  voucher_db:
    container_name: rd_voucher_db
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/data/voucher_db:/var/lib/mysql
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db
      MYSQL_PASSWORD: db@123
      TZ: UTC
    networks:
      - vpc

  nginx:
    container_name: rd_nginx
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa_host
    ports:
      - 80:80
    networks:
      vpc:
        aliases:
          - real.digital

  redis:
    container_name: rd_redis
    image: redis:alpine
    volumes:
      - ./docker/conf/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    hostname: redis
    expose:
      - 6379
    networks:
      - vpc

networks:
  vpc:
    driver: bridge
